-- Opt-in (vrf_cook_shaders): re-cook mesh.slang -> mesh.vshlib (all VTX_HAS_* permutations)
-- with the vshadersystem `vshaderc` host tool and regenerate the committed shaders/mesh_vshlib.h.
-- Off by default: the header is committed, so ordinary builds need no Slang toolchain.
if has_config("vrf_cook_shaders") then
    rule("vrf.cook_mesh_shaders")
        before_build(function (target)
            import("core.project.project")

            local pkg = project.required_package("vshadersystem~host")
            assert(pkg, "vrf_cook_shaders is on but the vshadersystem~host tool is unavailable")
            local vshaderc = path.join(pkg:installdir(), "bin", "vshaderc")
            if is_host("windows") and not os.isfile(vshaderc) then
                vshaderc = vshaderc .. ".exe"
            end
            assert(os.isfile(vshaderc), "vshaderc host tool not found: " .. vshaderc)

            local shaderRoot = path.join(target:scriptdir(), "shaders")
            local tmplib     = path.join(os.tmpdir(), "vrf_mesh.vshlib")
            os.vrunv(vshaderc, {"build", "--shader_root", shaderRoot, "-o", tmplib, "--no-wgsl"})

            -- bin2c: emit the committed byte-array header.
            local data  = io.readfile(tmplib, {encoding = "binary"})
            local lines = {
                "#pragma once",
                "// Generated from mesh.slang by `vshaderc build` (all VTX_HAS_* permutations, SPIR-V).",
                "// Regenerated by the vrf_cook_shaders build rule. Do not edit by hand.",
                "const unsigned char g_meshVshlib[] = {",
            }
            local line = "    "
            for i = 1, #data do
                line = line .. string.format("0x%02x,", data:byte(i))
                if i % 16 == 0 then
                    table.insert(lines, line)
                    line = "    "
                end
            end
            if #line > 4 then
                table.insert(lines, line)
            end
            table.insert(lines, "};")
            io.writefile(path.join(shaderRoot, "mesh_vshlib.h"), table.concat(lines, "\n") .. "\n")
            cprint("${green}[cook]${clear} regenerated shaders/mesh_vshlib.h")
        end)
    rule_end()
end

target("vrf_example_model_viewer")
    set_kind("binary")
    set_languages("cxx23")

    add_deps("vrf") -- inherits vrf's public headers + vri/glm/sdl3/glfw (+ imgui when enabled)

    if has_config("vrf_cook_shaders") then
        add_rules("vrf.cook_mesh_shaders")
    end

    -- native file-open dialog for the model picker (only when ImGui is enabled)
    if has_config("vrf_with_imgui") then
        add_packages("nativefiledialog-extended")
    end

    -- the compiled Slang shader headers are included as "shaders/..." relative to main.cpp
    add_includedirs(os.scriptdir())
    add_files("main.cpp")

    set_targetdir("$(builddir)/$(plat)/$(arch)/$(mode)/vrf_example_model_viewer")
