target("vrf-cache-bench")
    set_kind("binary")
    set_default(false)
    add_deps("vrf")
    add_packages("xxhash")
    add_files("cache_bench.cpp")
target_end()

target("vrf-bc7-bench")
    set_kind("binary")
    set_default(false)
    add_deps("vrf")
    add_packages("ktx")
    add_includedirs("../source/vrf/src", "../external/bc7enc")
    add_files("bc7_bench.cpp", "../external/bc7enc/bc7decomp.cpp")
target_end()
